Document: rtl-entropy
Title: Debian rtl-entropy Manual
Author: <insert document author here>
Abstract: This manual describes what rtl-entropy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtl-entropy/rtl-entropy.sgml.gz

Format: postscript
Files: /usr/share/doc/rtl-entropy/rtl-entropy.ps.gz

Format: text
Files: /usr/share/doc/rtl-entropy/rtl-entropy.text.gz

Format: HTML
Index: /usr/share/doc/rtl-entropy/html/index.html
Files: /usr/share/doc/rtl-entropy/html/*.html
